version: '3.1'
services:
  db:
    image: pestap/pg_db:1.0
    container_name: pg_db
    environment:
      - MARIADB_ROOT_PASSWORD=pgeti
      - MARIADB_DATABASE=astronomy_app
      - MARIADB_USER=astronomy_app_user
      - MARIADB_PASSWORD=pgeti
    volumes:
      - ./db_storage:/var/lib/mysql
    ports:
      - 3306:3306