version: '3.1'
services:
  db:
    build: .
    container_name: pg_db 
    environment:
      - MARIADB_ROOT_PASSWORD=pgeti
    volumes:
      - ./db_storage:/var/lib/mysql
    ports:
      - 3306:3306